---
title: "Assignments and grading"
editor: 
  mode: source
---

Your final course grade will be calculated as follows:

::: center-table
| Category      | Percentage |
|---------------|------------|
| Participation | 30%        |
| Midterm Paper | 25%        |
| Student-Led Discussion | 45%        |
:::

This course is a Satisfactory/Unsatisfactory course. An honest attempt at all assignments will result in a passing grade. Additionally, attendance in at least 12 out of 14 classes is required, as per Duke University House Courses.

::: center-table
| Letter Grade | Final Course Grade |
|--------------|--------------------|
| S            | \>= 60             |
| U            | \< 60              |
:::

::: callout-warning
We don't expect to give out any U's. Please work with us as much as possible/necessary!
:::

## Participation (30%)

Each class will involve discussion of several papers that have been selected for relevance/interest. Regular involvement in these discussions will result in a full score. If you need an exact number, try to speak out at least once each discussion. We want to hear your voice and about your interests!

::: callout-note
## For clarification

This doesn't mean that if you don't speak every class you will get a 0. Non-zero variance is expected! (If you don't know what that means, hopefully you'll learn during this course.)
:::

## Midterm Paper (25%)

At this point in the semester, we’ve reviewed many fundamental concepts and models in statistics. Although we still have more to cover, it’s important to reflect on and analyze some statistics on your own, and a write-up will help us accomplish this. 

*The prompt*: 
PPlease describe the basic mechanics of any statistical method we have encountered so far, including a simple explanation of the method, various indicators for the method, and when it should be used. Then, examine the use of the method in a published research paper that we have not seen in class and that you are not leading your discussion on. This should entail a brief overview of the article (background, topic context, motivation, variables, etc.), why the method was used, and how it supports the article’s conclusion.

Requirements:

-   650 word minimum.

-   MLA formatted citations.

-   Due beginning of class Week 8 *7:00PM Monday 10/19*

## Student-Led Discussions (45%)

Throughout the semester, you’ll be exposed to many different methods and models used in research. However, the most important part is being able to understand how others use (or misuse them) in real research. 

For the last half of the semester *10/19 - 11/23*, students will sign up to lead their own journal-club style discussions on a specific statistical topic. This will require several statistical papers, discussion questions, and an optional mini-lecture.

There are no limitations to what kind of paper is chosen – feel free to branch out and explore ideas we haven’t touched on or complex topics that are difficult to understand. However, the paper should be able to spark discussion/debate and should relate to your topic. 

*Prepare 5-10 potential discussion questions*, as well as your own “answers” to guide the class. Post your papers and discussion questions in the designated Canvas discussion one week before your discussion section by the *previous Monday at 11:59 PM*, so others will have time to review the material and read the paper.

Additionally, if you feel that it is necessary to do preliminary research on the topic in case your classmates have questions, or you’d like to provide a brief overview of a subject, that is an option. If you choose to explain a topic during class, you must make minimal use of electronic materials.

During the actual discussion section, you are not expected to ask all the questions, and feel free to come up with questions or discussion points that you have not prepared during the section. These discussion sections will aim to be *45-60 minutes long*, so prepare enough content for the time allotted! Our first half of the course should serve as a guide for what a discussion would look like.

::: callout-note
## Discussion Section Sign-Up

A sign-up for discussion sections will be sent out within the first two weeks of class! Stay tuned for a post on Canvas.
:::
